### ISSUE TITLE
Outstanding map script content

### ISSUE THREAD

**Issue by itsdarsh** [Rangi42/polishedcrystal#845]
See files in [material/*.txt](https://github.com/Rangi42/polishedcrystal/tree/master/material) for some concept dialog that could apply to these.

- [ ] The Lavender Town event involving Soul House, Pokémon Tower, Mr. Fuji, Agatha, and the SilphScope2 (see #1068)
- [ ] Trainers and NPCs in Rugged Road, Snowtop Mountain, and its Pokémon Center (see #1059)
  - See [material/pokeathlon-dialog.txt](https://github.com/Rangi42/polishedcrystal/blob/master/material/pokeathlon-dialog.txt)
  - One of them could be like [this guy](https://64.media.tumblr.com/d201bb5b8806c4d8ca98e882a01cceca/327b7835d57cf1a8-1a/s640x960/7e8ed3177b7045abe279e9f22cacca50a1eda1c2.pnj)
- [ ] Shamouti Island
  - [ ] Trainers with "TODO" dialog and Bulbasaurs
    - See [material/shamouti.txt](https://github.com/Rangi42/polishedcrystal/blob/master/material/shamouti.txt)
  - [ ] Tourist Center
  - [ ] Hotel rooms (vary like [Kalos hotels](https://bulbapedia.bulbagarden.net/wiki/Kalos_hotels))
    - See [material/hotel-trainers.txt](https://github.com/Rangi42/polishedcrystal/blob/master/material/hotel-trainers.txt)
  - [ ] Shamouti Hotel's Oasis Restaurant (like [Seven Stars](https://bulbapedia.bulbagarden.net/wiki/Seven_Stars_Restaurant) in DPPt; uses `WAITER`/`WAITRESS` trainer classes)
  - [ ] Beautiful Beach Villa, with Caitlin and Darach
    - See [material/caitlin-interview.txt](https://github.com/Rangi42/polishedcrystal/blob/master/material/caitlin-interview.txt)
    - "She was an HGSS Battle Frontier boss before moving to Unova and joining the Elite 4, and I wanted to add some justification for that change. The basic idea is she's in her villa, afraid of her own psychic powers (see [her quotes](https://bulbapedia.bulbagarden.net/wiki/Caitlin/Quotes)), sleeping most of the time; Darach battles you since she's indisposed. (He's very loyal and protective, but maybe too much so.) But when you come back later, after achieving more things yourself, she's realized that she can be herself too. Darach agrees that he'll miss her but that she should go live her own life. She battles you, and there's some reward; maybe a doll decoration."
  - [ ] Fire, Ice, and Lightning Islands (unsure what to do with them)
- [ ] Valencia Island
  - [ ] New layout and tiles from Orange
  - [ ] Dialog or purpose for Charity, Hope, and Faith
  - [ ] Signs and NPCs, including on Route 49
- [ ] Saffron City's [Pokémon Trainer Fan Club](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Trainer_Fan_Club) (see #1370)
  - See [material/fanclub.txt](https://github.com/Rangi42/polishedcrystal/blob/master/material/fanclub.txt) for possible rough draft dialog
- [ ] Safari Zone rest houses
- [ ] Route 35 gatehouse
  - Have some workers on break from building the Pokéathlon, with a reference to how it'll never get done
- [ ] Various other gatehouses
  - See [material/gates.txt](https://github.com/Rangi42/polishedcrystal/blob/master/material/gates.txt)
- [ ] Use `NPC_TRADE_JEEVES` (in Shamouti Hotel?)

**Comment by Rangi42** [comment]
These are the latest Valencia Island and Route 49 maps from Orange:

<img width="1408" height="832" alt="Image" src="https://github.com/user-attachments/assets/5674b519-5bab-4f3f-b7d7-261978bb3c85" />

We could add a Berry Master here:

<img width="640" height="768" alt="Image" src="https://github.com/user-attachments/assets/96e955bc-be6c-4855-ad84-659c30849405" />

**Comment by Rangi42** [comment]
These are the latest Shamouti Island maps from Orange (although PC would *not* copy these directly, we can keep the three elemental islands being a small trio to the south, since they aren't a major quest):

<img width="2752" height="1984" alt="Image" src="https://github.com/user-attachments/assets/2c394a28-1a22-4694-9d25-4b09a4a3577a" />

@PiaCarrot does plan to revise them further, with new tiles like better hanging lanterns:

<img width="70" height="30" alt="Image" src="https://github.com/user-attachments/assets/6c0f957e-5469-4c2d-be24-020ca92bf5e7" />
